version: "3"

services:

  editking-backend:
    container_name: editking-backend
    image: ozing/editking-server
    ports:
      - 8080:8080

  redis:
    container_name: redis_boot
    image: redis:alpine
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  nginx:
    container_name: nginx
    image: ozing/editking-nginx
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - editking-backend