version: "3"

services:

  editking-backend:
    container_name: editking-backend
    image: ozing/editking-server
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: ozing/editking-nginx
    ports:
      - 80:80
    depends_on:
      - editking-backend